services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - bases_dev:/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=mike
      - POSTGRES_DB=bases_dev

volumes:
  bases_dev:
    driver: local
