name: Build Docker images

on:
  push:
    branches: ['main']

jobs:
  build-and-push-dockerfile-image:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            mikecebul/bases:latest
          platforms: linux/amd64
          secrets: |
            DATABASE_URI=${{ secrets.DATABASE_URI }}
            NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }}
            PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}
            S3_ENABLED=${{ secrets.S3_ENABLED }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            NEXT_PUBLIC_IS_LIVE=${{ secrets.NEXT_PUBLIC_IS_LIVE }}
            NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
            NEXT_PUBLIC_UPLOAD_PREFIX=${{ secrets.NEXT_PUBLIC_UPLOAD_PREFIX }}
            NEXT_PUBLIC_USAEPAY_KEY=${{ secrets.NEXT_PUBLIC_USAEPAY_KEY }}
            NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_PORT=${{ secrets.EMAIL_PORT }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
            PREVIEW_SECRET=${{ secrets.PREVIEW_SECRET }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}
            S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}
            S3_REGION=${{ secrets.S3_REGION }}
            S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}
            S3_BUCKET=${{ secrets.S3_BUCKET }}
            NEXT_PUBLIC_S3_HOSTNAME=${{ secrets.NEXT_PUBLIC_S3_HOSTNAME }}
            UNSPLASH_ACCESS_KEY=${{ secrets.UNSPLASH_ACCESS_KEY }}
